### ISSUE TITLE
gulpfile.babel.js browsersync issue

### ISSUE THREAD

**Issue by boldwade** [simpulton/eggly-es6#1]
Hi there. Thank you for the project! I've been experiencing an issue with reloading the project, I'm getting 

> [error] You tried to start Browsersync twice! To create multiple instances, use browserSync.create().init()

Is no one else experiencing this? 

Hi, I actually submitted a PR regarding, https://github.com/simpulton/eggly-es6/pull/2
Hope it helps.

**Comment by simpulton** [comment]
Hey @boldwade we've updated the branches to avoid the browsersync issue using much of the code from your pull request. Please verify that it is working correctly for you now. Thanks!

**Comment by boldwade** [comment]
Sweet! Thanks Lukas! Love your vids, man. Keep up the great work!
